name: null
favicon: null
layout_spectrum: 0.74907
typography_spectrum: 0.50743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141519'
    - '#f3fdff'
    - '#5a5e67'
    - '#c5beaf'
    - '#d56063'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 044cba12-5107-454b-8f95-0ba634028d73
    url: null
