name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141519'
    - '#f3fdff'
    - '#5a5e67'
    - '#c5beaf'
    - '#d56063'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: d8193edc-bb19-4c5f-a24d-7907f048c65e
    url: null
