name: null
favicon: null
layout_spectrum: 0.82895
typography_spectrum: 0.01316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: 27219a6f-4e26-4db9-b673-23cc32d62db2
    url: null
