name: Corey Sullivan
favicon: null
layout_spectrum: 0.76453
typography_spectrum: 0.00301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131418'
    - '#f3fdff'
    - '#5d616a'
    - '#a9acb1'
    - '#0075fc'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: follow
    item: d8193edc-bb19-4c5f-a24d-7907f048c65e
    url: null
